#!/usr/bin/env bash
#
# test-appimage-wayland-patch.sh — tests for the AppImage Wayland/EGL
# compatibility patch (`patch-appimage-wayland.sh` + `appimage/wayland-compat-hook.sh`).
#
# The patch exists because linuxdeploy over-bundles libwayland into the AppImage:
# the host's Mesa libEGL then talks to a years-old libwayland-client and
# eglGetDisplay() fails with EGL_BAD_PARAMETER, so WebKitWebProcess aborts and
# the window stays white. See crates/arm-app/RELEASE-NOTES or the repo issue.
#
# These tests use a synthetic AppDir fixture, so they need no build and no
# display. Run from anywhere:
#
#   ./scripts/test-appimage-wayland-patch.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PATCH_SCRIPT="$ROOT/scripts/patch-appimage-wayland.sh"
HOOK_NAME="arm-wayland-compat.sh"

failures=0
checks=0

check() {
  local description="$1"
  local expected="$2"
  local actual="$3"
  checks=$((checks + 1))
  if [ "$expected" = "$actual" ]; then
    echo "  ok   — $description"
  else
    echo "  FAIL — $description"
    echo "         expected: [$expected]"
    echo "         actual:   [$actual]"
    failures=$((failures + 1))
  fi
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# A stand-in for what linuxdeploy emits: an AppRun that sources its GTK hook and
# then execs the real binary, plus the over-bundled wayland libraries.
make_fixture_appdir() {
  local appdir="$1"
  mkdir -p "$appdir/apprun-hooks" "$appdir/usr/lib" "$appdir/usr/bin"
  cat > "$appdir/AppRun" <<'APPRUN'
#! /usr/bin/env bash

# autogenerated by linuxdeploy

# make sure errors in sourced scripts will cause this script to stop
set -e

this_dir="$(readlink -f "$(dirname "$0")")"

source "$this_dir"/apprun-hooks/"linuxdeploy-plugin-gtk.sh"

exec "$this_dir"/AppRun.wrapped "$@"
APPRUN
  chmod +x "$appdir/AppRun"
  echo 'export GDK_BACKEND=x11' > "$appdir/apprun-hooks/linuxdeploy-plugin-gtk.sh"
  : > "$appdir/usr/lib/libwayland-client.so.0"
  : > "$appdir/usr/lib/libwayland-egl.so.1"
}

# Sources the installed hook the way AppRun does — under `set -e`, in a clean
# environment — and reports the LD_PRELOAD it ends up with.
run_hook() {
  local appdir="$1"
  shift
  env -i \
    PATH="$PATH" \
    HOME="$HOME" \
    "$@" \
    bash -c "set -e; source '$appdir/apprun-hooks/$HOOK_NAME'; echo \"\${LD_PRELOAD:-}\""
}

echo "AppImage Wayland patch tests"

# --- the patch itself -------------------------------------------------------
APPDIR="$WORK/Fixture.AppDir"
make_fixture_appdir "$APPDIR"
"$PATCH_SCRIPT" --appdir "$APPDIR" > /dev/null

check "hook is installed into the AppDir" \
  "yes" \
  "$([ -f "$APPDIR/apprun-hooks/$HOOK_NAME" ] && echo yes || echo no)"

check "AppRun sources the hook" \
  "yes" \
  "$(grep -q "$HOOK_NAME" "$APPDIR/AppRun" && echo yes || echo no)"

check "hook is sourced before the app is exec'd" \
  "yes" \
  "$(awk -v hook="$HOOK_NAME" '
      index($0, hook) { hooked = NR }
      /^exec / { exec_line = NR }
      END { print (hooked && exec_line && hooked < exec_line) ? "yes" : "no" }
    ' "$APPDIR/AppRun")"

check "the bundled wayland libraries are left in place as a fallback" \
  "yes" \
  "$([ -f "$APPDIR/usr/lib/libwayland-client.so.0" ] && echo yes || echo no)"

"$PATCH_SCRIPT" --appdir "$APPDIR" > /dev/null
check "patching twice leaves a single source line (idempotent)" \
  "1" \
  "$(grep -c "$HOOK_NAME" "$APPDIR/AppRun")"

# --- hook behaviour ---------------------------------------------------------
HOST_LIBS="$WORK/host-libs"
mkdir -p "$HOST_LIBS"
: > "$HOST_LIBS/libwayland-client.so.0"
: > "$HOST_LIBS/libwayland-egl.so.1"

check "under Wayland the host libwayland is preloaded" \
  "$HOST_LIBS/libwayland-client.so.0:$HOST_LIBS/libwayland-egl.so.1" \
  "$(run_hook "$APPDIR" WAYLAND_DISPLAY=wayland-0 ARM_WAYLAND_LIB_DIRS="$HOST_LIBS")"

check "XDG_SESSION_TYPE=wayland alone also triggers the preload" \
  "$HOST_LIBS/libwayland-client.so.0:$HOST_LIBS/libwayland-egl.so.1" \
  "$(run_hook "$APPDIR" XDG_SESSION_TYPE=wayland ARM_WAYLAND_LIB_DIRS="$HOST_LIBS")"

check "outside Wayland nothing is preloaded" \
  "" \
  "$(run_hook "$APPDIR" XDG_SESSION_TYPE=x11 ARM_WAYLAND_LIB_DIRS="$HOST_LIBS")"

check "with no host libwayland the bundled copies stay in charge" \
  "" \
  "$(run_hook "$APPDIR" WAYLAND_DISPLAY=wayland-0 ARM_WAYLAND_LIB_DIRS="$WORK/nonexistent")"

# LD_PRELOAD is set inside the shell rather than passed into it, so the test
# shell itself does not try to load the stand-in library.
check "an existing LD_PRELOAD is preserved, ours taking precedence" \
  "$HOST_LIBS/libwayland-client.so.0:$HOST_LIBS/libwayland-egl.so.1:/opt/other.so" \
  "$(env -i PATH="$PATH" HOME="$HOME" WAYLAND_DISPLAY=wayland-0 ARM_WAYLAND_LIB_DIRS="$HOST_LIBS" \
      bash -c "set -e; export LD_PRELOAD=/opt/other.so; source '$APPDIR/apprun-hooks/$HOOK_NAME'; echo \"\${LD_PRELOAD:-}\"")"

check "only the first match per library is preloaded" \
  "$HOST_LIBS/libwayland-client.so.0:$HOST_LIBS/libwayland-egl.so.1" \
  "$(run_hook "$APPDIR" WAYLAND_DISPLAY=wayland-0 ARM_WAYLAND_LIB_DIRS="$HOST_LIBS:$HOST_LIBS")"

check "sourcing the hook under set -e never aborts AppRun" \
  "still-running" \
  "$(env -i PATH="$PATH" HOME="$HOME" XDG_SESSION_TYPE=x11 \
      bash -c "set -e; source '$APPDIR/apprun-hooks/$HOOK_NAME'; echo still-running")"

# --- failure handling -------------------------------------------------------
BROKEN="$WORK/Broken.AppDir"
mkdir -p "$BROKEN"
check "a directory that is not an AppDir is rejected" \
  "failed" \
  "$("$PATCH_SCRIPT" --appdir "$BROKEN" > /dev/null 2>&1 && echo ok || echo failed)"

echo
if [ "$failures" -gt 0 ]; then
  echo "$failures of $checks checks FAILED"
  exit 1
fi
echo "all $checks checks passed"
